<?php

// $Id$


/**
 * @file
 * Configuration module for islandora_solr_search.module
 */


/**
 * Implementation of hook_alter_form.
 * Adds this module's configuration options to islandora_solr_search's configuration page.
 */

function islandora_solr_config_form_islandora_solr_admin_settings_alter(&$form, &$form_state) {
  $table_module   = 'islandora_solr_config';
  $table_file     = 'IslandoraSolrResultsTable.inc';
  $table_class    = 'IslandoraSolrResultsTable';
  $table_method   = 'displayResults';

  $maps_module   = 'islandora_solr_config';
  $maps_file     = 'IslandoraSolrResultsMaps.inc';
  $maps_class    = 'IslandoraSolrResultsMaps';
  $maps_method   = 'displayResults';

  $config_options = $form['islandora_solr_config_options']['#options'];
  $config_options["${table_module}~${table_file}~${table_class}~${table_method}"] = 'Table';
  $config_options["${maps_module}~${maps_file}~${maps_class}~${maps_method}"] = 'Maps';
  $form['islandora_solr_config_options']['#options'] = $config_options;
}

/**
 * Implements hook_islandora_solr_search_primary_display()
 */
function islandora_solr_config_islandora_solr_search_primary_display() {
  return array(
    // 'machien-name' = array(
    //   'name' => 'Human Readable Name',
    //   'module' => 'module_name',
    //   'file' => 'FileName.inc',
    //   'class' => 'ClassName',
    //   'function' => 'function_name',
    //   'description' => 'A description of the display profile',
    // );
    'simple_table' => array(
      'name' => t('Simple Table'),
      'module' => 'islandora_solr_config',
      'file' => 'IslandoraSolrResultsTable.inc',
      'class' => "IslandoraSolrResultsTable",
      'function' => "displayResults",
      'description' => t("A simple tabular output"),
    ),
    'maps' => array(
      'name' => t('Maps'),
      'module' => 'islandora_solr_config',
      'file' => 'IslandoraSolrResultsTable.inc',
      'class' => "IslandoraSolrResultsTable",
      'function' => "displayResults",
      'description' => t('A tabular output for maps. Depends upon the existence of a TN datastream in fedora objects returned as results.')
    ),
  );
}

/**
 * Implementation of hook_help()
 */

function islandora_solr_config_help($path, $arg) {

  switch ($path) {
    case 'admin/help#islandora_solr_config':
      return t("When 'Sample Solr Configuration Settings' is selected from the configuration drop-down in the<br />
        !page the following settings will be used.
        <ul>
        <li>Module - islandora_solr_config</l1>
        <li>File - IslandoraSolrResultsTable.inc</l1>
        <li>Class - IslandoraSolrResultsTable</l1>
        <li>Method - displayResults</l1>
        </ul>
        ", array('!page' => l("Islandora_solr_search configuration page", 'admin/settings/islandora_solr_search'),)


      );
  }
}

