<?php

// $Id$


/**
 * @file
 * Configuration module for islandora_solr_search.module
 */


/**
 * Implementation of hook_alter_form.
 * Adds this module's configuration options to islandora_solr_search's configuration page.
 */

function IslandoraSolrConfig_form_islandora_solr_admin_settings_alter(&$form, &$form_state) {
  $module   = 'IslandoraSolrConfig';
  $file     = 'CustomizedResults.inc';
  $class    = 'CustomizedIslandoraSolrResults';
  $method   = 'displayResults';
  $config_options = $form['islandora_solr_config_options']['#options'];
  $config_options["${module}~${file}~${class}~${method}"] = 'Sample';
  $form['islandora_solr_config_options']['#options'] = $config_options;
}


/**
 * Implementation of hook_help()
 */

function IslandoraSolrConfig_help($path, $arg) {

  switch ($path) {
    case 'admin/help#IslandoraSolrConfig':
      return t("When 'Sample Custom Settings' is selected from the conguration dropdown in the<br />
        !page the following settings will be used.
        <ul>
        <li>Module - IslandoraSolrConfig</l1>
        <li>File - CustomizedResults.inc</l1>
        <li>Class - IslandoraSolrResults</l1>
        <li>Method - displayResults</l1>
        </ul>
        ", array('!page' => l("Islandora_solr_search configuration page", 'admin/settings/islandora_solr_search'),)


      );
  }
}

